# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-10'    # Swift Concurrency implementation
  pod 'KMPNativeCoroutinesCombine', '1.0.0-ALPHA-10'  # Combine implementation
  pod 'KMPNativeCoroutinesRxSwift', '1.0.0-ALPHA-10'  # RxSwift implementation
  pod 'Kingfisher'                                    # Image loading
  pod 'shared', :path => '../shared'                  # Adding development pod, that contains shared framework

end
